# Generated by Django 5.2.9 on 2025-12-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
