# Generated by Django 5.2.9 on 2025-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_useractivity_alter_users_is_active_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='profile_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
